version: "3"
services:
  web:
    depends_on:
      - postgres
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    # replace username/repo:tag with your name and image details
    image:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 4000:4000
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
